// src/App.svelte
<script lang="ts">
  import Hero from './articles/Hero.svelte'
  import TopBar from './articles/TopBar.svelte'
  import WIP from './articles/WIP.svelte'
</script>

<main>
  <Hero />
  <div class="last-section">
    <WIP />
  </div>
</main>

<TopBar />

<style lang="scss">
  main {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    overflow: hidden;

    background: black;
    color: white;
  }

  .last-section {
    width: 100%;
    height: calc(100vh - (4vh + 2vh));
  }
</style>

// src/app/page.tsx
'use client'

import Markdown from 'react-markdown'
import styled from 'styled-components'

const Main = styled.main`
	display: flex;
	justify-content: center;
	align-items: center;
	flex-direction: column;
	background-color: red;
	border-radius: 1rem;
	margin: 2.5% 10%;
	padding: 1rem;
`

const PFP = styled.img`
	border-radius: 25%;
	width: 5rem;
	height: 5rem;
`

export default async function Page() {
	const README = await (
		await fetch(
			'https://raw.githubusercontent.com/iivusly/iivusly/main/README.md'
		)
	).text()

	return (
		<Main>
			<PFP src={'https://github.com/iivusly.png'} />
			<h1>Hello</h1>
			<div className="markdown-body">
				<Markdown>{README}</Markdown>
			</div>
		</Main>
	)
}
